openapi: "3.0.2"
info:
  title: "Captions Check"
  version: "1.0"
  description: ""
servers:
  - url: https://localhost:3000/api

components:
  schemas:
    Org:
      description: "組織：成員可檢視內部所有字幕任務清單"
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: "兔兔教"
        description:
          type: string
          example: "哈囉直播字幕校稿組！"
        isPublic:
          type: boolean
          default: true
        createDate:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        manager:
          $ref: "#/components/schemas/User"
        members:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      description: "人員資訊"
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: "小白"
        email:
          type: string
          example: "little.white.liar@gmail.com"
        token:
          type: string
          format: sha-256
        createDate:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        orgs:
          type: array
          items:
            $ref: "#/components/schemas/Org"
        isActive:
          type: boolean
          default: true
    Task:
      description: "檢核任務"
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        title:
          type: string
          example: "「React 讀書班」來切 Login Form"
        url:
          type: string
          format: url
          example: "https://www.youtube.com/watch?v=IfaTpyhaGlg"
        createDate:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        org:
          $ref: "#/components/schemas/Org"
        isComplete:
          type: boolean
          default: true

paths:
  /api/v1/{orgId}/Task:
    get:
      summary: "取得組織內的任務清單"
      parameters:
        - in: path
          name: orgId
          required: true
          description: org id
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      type:
                        description: error type
                        type: string
                      message:
                        description: error message
                        type: string



